# Generated by Django 4.0.4 on 2022-05-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_links_link_name_alter_links_name_alter_profil_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='link',
            field=models.URLField(max_length=300),
        ),
    ]
