# Generated by Django 4.0.4 on 2022-06-07 12:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_profil_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
