# Generated by Django 4.0.4 on 2022-06-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_profil_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='color',
            field=models.CharField(choices=[('cloudy white', 'cloudy white'), ('Air white', 'Air white'), ('Aurora B', 'Aurora B'), ('Mid Night', 'Mid Night'), ('Cool Grey', 'Cool Grey')], default='cloudy white', max_length=300),
        ),
    ]
